### ISSUE TITLE
変数の数

### ISSUE THREAD

**Issue by C0B21137** [syara1479/ProjExD#6]
https://github.com/syara1479/ProjExD/blob/f512ce7ddeff927cda3aae66be853cc8eb95ed32/ex02/calc.py#L48
for文で回しているときのiを活用すれば、変数の数を一つ減らせると思います。
変数が多いとコードが分かりづらくなると思うのでご一考ください。

**Comment by syara1479** [comment]
変数を減らそうと努力しましたがどのようにしても変数を減らすことができませんでした。申し訳ありません。
